### ISSUE TITLE
Error thrown on apiKeysRemoveKey

### ISSUE THREAD

**Issue by waterloomatt** [zend-patterns/ZendServerSDK#100]
Running `php /bin/zs-client.phar apiKeysRemoveKey --ids="3" --target=localhost` results in _Could not match to a controller_

> root@lhorizon:/bin# php /bin/zs-client.phar apiKeysRemoveKey --ids="3" --target=localhost
> ZendServerWebApi Client version 1.2
> Zend Server Client v1.0
> 
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> ZendServerWebApi
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> * apiKeysRemoveKey --ids= [--target=] [--zsurl=] [--zskey=] [--zssecret=] [--zsversion=] [--http=] [--output-format=]
> 
> Remove a WebAPI Key.
>   --ids              Id of the key
>   --output-format    Output format. Default is "xml", but you can use json or kv(for key-value)
> 
> -------------------------------------------------------------------
> 
> Reason for failure: Could not match to a controller

**Comment by slaff** [comment]
@waterloomatt Can you provide the version of Zend Server that you are using ?

**Comment by waterloomatt** [comment]
PHP Version 7.3.27
Zend Server Version: 2019.0.7
Build: 125795
