### ISSUE TITLE
Deployment scripts not properly created into zpk archive

### ISSUE THREAD

**Issue by sophpie** [zend-patterns/ZendServerSDK#34]
Hi there,

If you put your deployment scripts like post_stage.php into a /deploy directory at the root of the app the resulting package with packZpk will show something like this : /deploy/deploy/post_stage.php.
When deploying on zend server deployment scripts will be not played at all.
It is ok with the same code packaged with Zend Studio.

**Comment by slaff** [comment]
That issue should be fixed in f56d829888a58a5d6966c75062cd2ad8d9bea4f0.
