### ISSUE TITLE
Add support for a delimiter in multiple params that is not a shell special character.

### ISSUE THREAD

**Issue by slaff** [zend-patterns/ZendServerSDK#45]
Instead of "x=1&z=test" to use something like "x=1 y=test".

**Comment by slaff** [comment]
One use-case from Amir Friedman: 

"- it's not possible to have directives values containing the "&" character (I couldn't find a way to escape the character). 
For instance, it's not possible to use this command :
php zs-client.phar configurationStoreDirectives --directives="error_reporting=E_ALL & ~E_NOTICE"
"

**Comment by wrightkennethj** [comment]
class module{
public function extern escape{

configurationStoreDirectives --directives="error_reporting=E_ALL & ~E_NOTICE & ~E_LOG"}}
 


     On Monday, 13 July 2015, 10:38, slaff <notifications@github.com> wrote:
   

 One use-case from Amir Friedman: "- it's not possible to have directives values containing the "&" character (I couldn't find a way to escape the character). 
For instance, it's not possible to use this command :
php zs-client.phar configurationStoreDirectives --directives="error_reporting=E_ALL & ~E_NOTICE"
"—

**Comment by boedah** [comment]
Even with

* strong quoting: `--directives='error_reporting=E_ALL & ~E_NOTICE'`
* or escaping: `--directives="error_reporting=E_ALL \& ~E_NOTICE"`

?
