### ISSUE TITLE
Autodetect Zend Server version

### ISSUE THREAD

**Issue by weierophinney** [zend-patterns/ZendServerSDK#48]
Currently, when creating an SDK target, you have the option of specifying the Zend Server version via the `--version` option. If you fail to do so, it defaults to "6.3".

This is not useful, particularly for the upcoming version 8, where using that version results in the SDK being unusable when that target is specified.

The better path would be to try and connect to the Zend Server API and determine the version from the API -- and to potentially prompt the user for the version if the API cannot provide that information (even better: provide information in that prompt to guide the user to discover the version from the UI!).

**Comment by wrightkennethj** [comment]
You idiots.
Seriously the XMLHydrator is in a lot of deep water, waiting to condense and expand some file management system.
you need a try XMLHydrator {
                                            for XMLHydrator(
                                                                        use XMLDisplayWindow(window: height ='800', width='500')
                                                                        );
then XMLShellWindow(                                        use XMLHydrator(); then 
                                        use XMLDisplayWindow($shell_objects());
);};
Yours Kenny in Scotts Idiots



 


     On Monday, 13 July 2015, 16:20, slaff <notifications@github.com> wrote:
   

 Closed #48.—
