### ISSUE TITLE
packZpk is adding deployment scripts into scripts/scripts directory

### ISSUE THREAD

**Issue by swilczynski** [zend-patterns/ZendServerSDK#5]
It is creating scripts directory inside another scripts directory which makes Zend Server unable to unpack and execute deployment scripts like post_stage.php

This issue is probably caused by pack method of ZpkInvokable where it calls

$zpk->addFile($fullPath, $this->fixZipPath($baseDir.$path));

For scripts directory it tries to do

$zpk->addFile($fullPath, $this->fixZipPath('scripts/'.'scripts/post_stage.php'));

**Comment by ryanheath86** [comment]
I created a pull request for this issue and it now works for me.. 

I didn't see a fix in the latest release or dev version, so I'm not sure if this was fixed yet

https://github.com/zend-patterns/ZendServerSDK/pull/56
