### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by wrightkennethj** [zend-patterns/ZendServerSDK#54]
<?xml version="1.0"?>
<project name="APPNAME" basedir="." default="zpk">  
    <target name="zpk">
        <exec command="php /usr/local/bin/zs-client.phar packZpk --folder='${project.basedir}' --destination='${project.basedir}' --name='application.zpk'" checkreturn="true"/>
    </target>
    <target name="deploy" depends="zpk">
<target filename="ZFS">
        <exec command="php /usr/local/bin/zs-client.phar installApp --zpk='${project.basedir}/application.zpk' --zsurl='${host}' --zskey='${key}' --zssecret='${secret}' --baseUrl='${base}' --userAppName='${app}' --userParams='${params}'" checkreturn="true"/>
    </target>
</project>

**Comment by wenwolf** [comment]
Can you please update the issue and give more information about it? Otherwise I have to close it due to lack of information  after some days.
