### ISSUE TITLE
Use of monitorCountIssuesListPredefinedFilter

### ISSUE THREAD

**Issue by ericovasconcelos** [zend-patterns/ZendServerSDK#55]
I've tried to use this method but everytime I get a response stating that the method is not available on the server. 

object(stdClass)#460 (3) { ["zendServerAPIResponse"]=> string(34) "http://www.zend.com/server/api/1.2" ["requestData"]=> object(stdClass)#475 (2) { ["apiKeyName"]=> string(7) "Unknown" ["method"]=> string(7) "default" } ["errorData"]=> object(stdClass)#482 (2) { ["errorCode"]=> string(13) "unknownMethod" ["errorMessage"]=> string(91) "The requested action 'monitorCountIssuesListPredefinedFilter' does not exist on this server" } } {"result":null}

It seams it reverts to use of the version 1.2 of the API in which it doesn't exists. But I've tried to force the use of version 1.7 adding the ';version=1.7; to the headers (Content-type and Accept) but it still reverts to 1.2. 

I might be doing something wrong on the versioning negotiation, or there is a bug the reverts to 1.2 on this method. I've tried it on versions 6.3 and 8 of Zend Server.

**Comment by wrightkennethj** [comment]
You would need to change the script of zendserver/api/1.2 to I think this would be something like: -
$apiKeyName="ZendServer"$add.zend_server_api$update zend_server_api_version:1.'+1' 

     On Thursday, 15 January 2015, 17:11, ericovasconcelos <notifications@github.com> wrote:
   

 I've tried to use this method but everytime I get a response stating that the method is not available on the server. object(stdClass)#460 (3) { ["zendServerAPIResponse"]=> string(34) "http://www.zend.com/server/api/1.2" ["requestData"]=> object(stdClass)#475 (2) { ["apiKeyName"]=> string(7) "Unknown" ["method"]=> string(7) "default" } ["errorData"]=> object(stdClass)#482 (2) { ["errorCode"]=> string(13) "unknownMethod" ["errorMessage"]=> string(91) "The requested action 'monitorCountIssuesListPredefinedFilter' does not exist on this server" } } {"result":null}It seams it reverts to use of the version 1.2 of the API in which it doesn't exists. But I've tried to force the use of version 1.7 adding the ';version=1.7; to the headers (Content-type and Accept) but it still reverts to 1.2. I might be doing something wrong on the versioning negotiation, or there is a but the reverts to 1.2 on this method. I've tried it on versions 6.3 and 8 of Zend Server.—

**Comment by slaff** [comment]
I can confirm the issue. Most probably the documentation (http://files.zend.com/help/Zend-Server/zend-server.htm#the_monitorcountissueslistpredefinedfilter_method.htm) is wrong.

**Comment by wrightkennethj** [comment]
Can you add try HTTP method "GET_POST_FILTER_MONITOR"
For example
CDATA[ MOINTOR_HTTP_POST ]CDATA[ GET_HTTP_POST_FILTER_MONITOR ]
 

     On Friday, 16 January 2015, 15:54, slaff <notifications@github.com> wrote:
   

 I can confirm the issue. Most probably the documentation (http://files.zend.com/help/Zend-Server/zend-server.htm#the_monitorcountissueslistpredefinedfilter_method.htm) is wrong. —

**Comment by wrightkennethj** [comment]
I think??
HTTP protocall_responce_filter_monitorHTTP ? protocall 404
HTTP ? protocall 440
 

     On Friday, 16 January 2015, 16:06, Kenneth Wright <kennethjwright@yahoo.co.uk> wrote:
   

 Can you add try HTTP method "GET_POST_FILTER_MONITOR"
For example
CDATA[ MOINTOR_HTTP_POST ]CDATA[ GET_HTTP_POST_FILTER_MONITOR ]
 

     On Friday, 16 January 2015, 15:54, slaff <notifications@github.com> wrote:
   

 I can confirm the issue. Most probably the documentation (http://files.zend.com/help/Zend-Server/zend-server.htm#the_monitorcountissueslistpredefinedfilter_method.htm) is wrong. —

**Comment by ericovasconcelos** [comment]
Hi Slaff, i've tried the new code and worked perfectly. Thanks.
