### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by boedah** [zend-patterns/ZendServerSDK#59]
Are there any plans to add automated tests to this project?
I think this is crucial, as:

* the documentation is sparse (especially for the scriptsdir stuff)
* users will download the latest phar (according to the README), breaking existing functionality can be hard to spot (especially as there are no released versions or a CHANGELOG)

First candidates I see would be the scriptsdir stuff (as I also had the most problems with it), to address #34, #56, #57.

In the first step, only package creation can be tested, not deploying itself (which could be added later on). So errors like #35 could be catched.

E.g. I could not find documentation on how the "persistent resources" feature is working (which did not in my case): http://files.zend.com/help/Zend-Server/content/understanding_the_package_structure.htm

**Comment by slaff** [comment]
CI using Travis is now part of the project.( See commits: ecdab080090b12a6ead50e1babe468e6b22f0653, f56d829888a58a5d6966c75062cd2ad8d9bea4f0,

**Comment by boedah** [comment]
:+1: !
