### ISSUE TITLE
When using the filterSave method, the zs-client.phar sends an HTTP method error

### ISSUE THREAD

**Issue by ericovasconcelos** [zend-patterns/ZendServerSDK#63]
I've tried to use a method to import a filter rule from one server to other, but when using the filterSave method, it requires a POST method:

php zs-client.phar filterSave --type=issue --target=zst --name=CLIQueryAllEvents --data={"applicationIds":[29]}
2015-04-30T16:24:43-03:00 ERR (3): This action requires a HTTP POST method<zendServerAPIResponse xmlns="http://www.zend.com/server/api/1.7">
    <requestData>
        <apiKeyName><![CDATA[zendcmd]]></apiKeyName>
        <method>filterSave</method>
    </requestData>
<errorData>
 <errorCode>unexpectedHttpMethod</errorCode>
 <errorMessage><![CDATA[This action requires a HTTP POST method]]></errorMessage>
</errorData></zendServerAPIResponse>
======================================================================
   The application has thrown an exception!
======================================================================
 ZendServerWebApi\Model\Exception\ApiException
 This action requires a HTTP POST method

**Comment by wrightkennethj** [comment]
I think that the FilterSave method and POST, that would refer to the chroot with a shroot(shell_root); all in php
but the SaveTarget is a new theory "zst", try "zst_POST"
use unexpected throw method zst_POST would be a " prototype_protocall_callback_POST( )"
under file_target_"zst_POST{}" raise shroot && cmd chroot in file_target_POST{};
Regards Kenny 


     On Thursday, 30 April 2015, 20:26, ericovasconcelos <notifications@github.com> wrote:
   

 I've tried to use a method to import a filter rule from one server to other, but when using the filterSave method, it requires a POST method:php zs-client.phar filterSave --type=issue --target=zst --name=CLIQueryAllEvents --data={"applicationIds":[29]}
2015-04-30T16:24:43-03:00 ERR (3): This action requires a HTTP POST method
 
 <![CDATA[zendcmd]]>
 filterSave
 

 unexpectedHttpMethod
 <![CDATA[This action requires a HTTP POST method]]>


 The application has thrown an exception!
ZendServerWebApi\Model\Exception\ApiException
 This action requires a HTTP POST method—

**Comment by slaff** [comment]
@ericovasconcelos The issue is fixed in the latest phar ( https://github.com/zend-patterns/ZendServerSDK/raw/master/bin/zs-client.phar ) version. Make sure also to use query string formatting for passing the data and not json formatting. The correct way to test the filterSave with the data that you have provided will be:

php zs-client.phar filterSave --type=issue --target=zst --name=CLIQueryAllEvents --data="applicationIds[]=29"
