### ISSUE TITLE
Build PHAR with fixed webapi method jobqueueRulesList

### ISSUE THREAD

**Issue by zvikazend** [zend-patterns/ZendServerSDK#65]
Please rebuild phar and commit, once this pull request is merged:
https://github.com/zend-patterns/ZendServerWebApiModule/pull/14
Note: a ZPK library for Zend Server is needed as well.
Thanks!
ZD

**Comment by slaff** [comment]
Done. See https://github.com/zend-patterns/ZendServerSDK/commit/def952f6904333fdc9625635a3832e2be4fe2e58
