### ISSUE TITLE
Includes not work for library

### ISSUE THREAD

**Issue by stalxed** [zend-patterns/ZendServerSDK#70]
Hello!
I found bug in command:
> php bin/zs-client.phar packZpk --folder="<folder-where-the-PHP-code-is>" --destination="<folder-where-the-package-will-be-created>"

For application appdir.includes in file deployment.properties work good.
But for library this option not work(includes all directories and files of projects, even git directory!).
Please, if you can, fix it please.

**Comment by wrightkennethj** [comment]
I found the debug in command:
php cgi-bin/zs-client.phar packetZpk --folder="" --target="" 
#Fixitforme{$DEBUG};
final --destination="" 
include app.dir in file depolyment.property;
for library{                    use zend in this option of library;
            };

then you stalex files.
 


     On Friday, 24 July 2015, 2:34, stalxed <notifications@github.com> wrote:
   

 Hello!
I found bug in command:
php bin/zs-client.phar packZpk --folder="" --destination=""
For application appdir.includes in file deployment.properties work good.
But for library this option not work.
Please, if you can, fix it please.—

**Comment by slaff** [comment]
If that is the  behaviour in Zend Studio then we will fix it.

**Comment by stalxed** [comment]
Thanks! It works!
