### ISSUE TITLE
Allow appInstall to <default-server> vhost

### ISSUE THREAD

**Issue by PhearZero** [zend-patterns/ZendServerSDK#75]
Currently no option in appInstall to let the application use a zend server "default-server" vhost

**Comment by slaff** [comment]
PhearZero - the installApp command has an option called "baseUri". Use it to point which existing zend server vhost you want to use. Let say you have a vhost called mycompany.com then you can deploy your application and link it to that host using a command similar to the one below

```bash
php zs-client.phar --zpk=<path/to/application>.zpk --baseUri=http://mycompany.com --target=<zend-server-target-name>
```

**Comment by PhearZero** [comment]
Sorry for the delay. I am refering to the default vhost which can be deployed via the lighttp GUI as well as [zs-manage via the appDeploy with the -d flag](http://files.zend.com/help/Zend-Server/content/app-deploy.htm). I can deploy no problem to custom vhosts. I am using the [ZendBamboo pattern](https://github.com/zend-patterns/ZendServerBamboo) which uses zs-client. There is no way in the cli to deploy to the default vhost via zs-client as it does with zs-manage app-deploy -p build.zpk -d

**Comment by slaff** [comment]
Ok, yes it is possible to deploy on the default vhost. Just use the following flag --defaultServer=TRUE. From the help of the command you can see that

```bash
php zs-client.phar installApp --help 
```

--defaultServer =TRUE allows to "Deploy the application on the default server. The provided base URL will be ignored and replaced with '<default-server>'. If this parameter and createVhost are both used, createVhost will be ignored. The default value is FALSE." 

Example:
```bash
php zs-client.phar --defaultServer=TRUE --zpk=<path/to/application>.zpk --baseUri=http://mycompany.com/some/path --target=<zend-server-target-name>
```
