### ISSUE TITLE
Dependency restriction to ZF 2.4.x

### ISSUE THREAD

**Issue by alexb-uk** [zend-patterns/ZendServerSDK#81]
Hi,

I'm having an issue installing this package via Composer due to a version constraint mismatch between ZF 2.4.x and 2.5.x. I'm doing a spike test project using the latest Apigility Skeleton project but can't get this to work.

```
> composer require --dev zenddevops/client
Using version ^1.1 for zenddevops/client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove zendframework/zendframework 2.5.2
    - Conclusion: don't install zendframework/zendframework 2.5.2
```

I was about to fork the repo and test to see if ZendServerSDK really does have a dependency on 2.4 but thought I might save myself some time if I posted a message here first.

If you aren't sure I can give it a quick try but having never used the ZendServerSDK before I'm not 100% confident I will spot any issues.

Many Thanks

Alex

**Comment by slaff** [comment]
Getting the source code is needed if you want to extend further the zs-client itself.
If you just want to use it then get the phar file: https://github.com/zend-patterns/ZendServerSDK/raw/master/bin/zs-client.phar.

**Comment by alexb-uk** [comment]
I was hoping to be able to use Composer to manage the dependency on ZendServerSDK via require-dev. AFAIK you cannot get Composer to pull in a single PHAR file without the mismatched dependencies.

I did fork master to try it and so far its worked perfectly on PHP 5.6 and 2.5.2.
See: https://github.com/alexb-uk/ZendServerSDK/commit/ac45affc9d07e89a952288fab26919497c634b1e

Tested so far includes: Adding target, initZpk, monitorGetIssuesListPredefinedFilter, packZpk and installApp.

Would you prefer to limit the ZF dependency to version 2.4.* or could I submit a Pull Request to get it relaxed to >=2.4.0, <3.0.0.

Thanks

**Comment by slaff** [comment]
@alexb-uk 2.4.0 is the [Long Term Zend Framework 2 version](http://framework.zend.com/long-term-support/). I am fine to relax the rules.  It would be great if your PR includes also UnitTests for Service Manager and Event Manager. The reason for this is that they were refactored recently and are not backwards compatible (https://github.com/zendframework/zend-eventmanager/tree/develop/doc/book/migration). This ways we can spot fast enough if there are issues with the latest 2.x Event or Service Manager if somebody decides to break compatibility.

**Comment by alexb-uk** [comment]
I had not heard of the LTS for ZF2 so thanks a lot for pointing that out.

I'll have a think, I might consider rolling back our project to the LTS version instead.

Cheers

**Comment by alexb-uk** [comment]
I've had a browse around the source code and it appears from a very basic search that ZendServerSDK itself doesn't have any dependency on Service Manager or Event Manager!?!?

The only sub-dependency was the zendframework/zend-i18n which requires them both. But we should rely on the maintainers of the zend-i18n module to have good integration tests.

If that is the case I would suggest we're safe to proceed with relaxing the constraint BUT we would need to be careful if anyone added a dependency specific to 2.4.x or 2.5.x in the future.

I've run the unit tests on my local dev environment all passed (PHP 5.6 and ZF 2.5.2)

Thoughts?

**Comment by slaff** [comment]
Send me Pull Request request  :)

**Comment by wrightkennethj** [comment]
I though this would have an in-dependency module class in Event-Service-Management which should combine with any class module.
Add it in PHP.
eg. 
global{
run local_environment(~"/zendframework/zend-i18n/");
public static class EventServiceManager() {                return EventServiceManager()                            }return global();}


 


    On Tuesday, 1 December 2015, 16:58, slaff <notifications@github.com> wrote:
 

 Send me Pull Request request :)

**Comment by alexb-uk** [comment]
@wrightkennethj sorry I didn't follow that :)

I'll send over a Pull Request now but feel free to ignore it if you guys think this requires some more consideration.

**Comment by wrightkennethj** [comment]
I thought that browsers and its codes should be simple?
Do this in PHP"! You idiots just fucking list it in. Don't use the MVC shite from Microsoft.
package EventServiceManagement();
OnArray_OnFunction_Global_Management(){
-chmod class  EventServiceManagement();
-onwait -onarray class callback EventService();
-pull -onrequest class EventService();
-pop -onLoad class HTTPEventServiceRequest();
-divMod -onLoad class XMLQueryQueue(                    HTTPEventServiceRequest();                )return package EventServiceManagement();}
return the fight you ugly idiots!
Yours Non-Microsoft Shite



 


    On Wednesday, 2 December 2015, 14:06, alexb-uk <notifications@github.com> wrote:
 

 @wrightkennethj sorry I didn't follow that :)I'll send over a Pull Request now but feel free to ignore it if you guys think this requires some more consideration.—
