### ISSUE TITLE
zs-client is compatible with ZF2 only

### ISSUE THREAD

**Issue by slaff** [zend-patterns/ZendServerSDK#84]
Change the composer.json definitions to use only ZF components that are compatible with version 2.

**Comment by wrightkennethj** [comment]
I want you to submit and surrender to the error failures in powershell hahahaha!
5 errors and where is your data callback on viewing error profiles??Hunt them down with apache error killer. Lol!

Yours Idoits 

    On Monday, 4 April 2016, 13:25, slaff <notifications@github.com> wrote:
 

 Change the composer.json definitions to use only ZF components that are compatible with version 2.—

**Comment by wrightkennethj** [comment]
Use the apache command promt to search. 

    On Monday, 4 April 2016, 13:25, slaff <notifications@github.com> wrote:
 

 Change the composer.json definitions to use only ZF components that are compatible with version 2.—
