### ISSUE TITLE
logsReadLines --lineToRead=

### ISSUE THREAD

**Issue by Schnaaf** [zend-patterns/ZendServerSDK#94]
when using zs-client.phar the value of the lineToRead parameter is not respected. Independent of this parameter value I always get 200 lines back.

The documentation of this parameter is puzzling as well:

"--lineToRead       How many lines to read. defaults to a certain system-wide configurable setting. Limited by another such setting."

What setting are they talking about?

**Comment by slaff** [comment]
I guess you are talking about the `logsReadLines` command.

```
logsReadLines --logName= [--serverId=] [--lineToRead=] [--filter=]
```

If yes, then I will check if Zend Server has the same command signature and see where is the issue coming from.

**Comment by Schnaaf** [comment]
Thanks for the swift fix @slaff
