### ISSUE TITLE
APIs getServerProfile and setServerProfile not recognized

### ISSUE THREAD

**Issue by zvikazend** [zend-patterns/ZendServerSDK#97]
These APIs are working against Zend Server 9.1, but not from zs-client (tried the latest zs-client.phar)

```
php zs-client.phar --target=local getServerProfile
php zs-client.phar --target=local setServerProfile --production=true/false
```

**Comment by slaff** [comment]
Docs:
http://files.zend.com/help/Zend-Server/content/the_getserverprofile_method.htm
http://files.zend.com/help/Zend-Server/content/the_setserverprofile_method.htm
